package google.apps.script;

@:require(google_apps_script)
@:native("DateTimeFormat")
@:enum abstract DateTimeFormat(String) from String to String {
	var ISO_8601 = "ISO_8601";
	var RFC_2822 = "RFC_2822";
	var DATE_FULL = "DATE_FULL";
	var DATE_LONG = "DATE_LONG";
	var DATE_MEDIUM = "DATE_MEDIUM";
	var DATE_SHORT = "DATE_SHORT";
	var TIME_FULL = "TIME_FULL";
	var TIME_LONG = "TIME_LONG";
	var TIME_MEDIUM = "TIME_MEDIUM";
	var TIME_SHORT = "TIME_SHORT";
	var DATE_TIME_FULL = "DATE_TIME_FULL";
	var DATE_TIME_LONG = "DATE_TIME_LONG";
	var DATE_TIME_MEDIUM = "DATE_TIME_MEDIUM";
	var DATE_TIME_SHORT = "DATE_TIME_SHORT";
	var DAY = "DAY";
	var HOUR_MINUTE = "HOUR_MINUTE";
	var HOUR_MINUTE_SECOND = "HOUR_MINUTE_SECOND";
	var HOUR24_MINUTE = "HOUR24_MINUTE";
	var HOUR24_MINUTE_SECOND = "HOUR24_MINUTE_SECOND";
	var MINUTE_SECOND = "MINUTE_SECOND";
	var MONTH = "MONTH";
	var MONTH_ABBR = "MONTH_ABBR";
	var MONTH_ABBR_DAY = "MONTH_ABBR_DAY";
	var MONTH_DAY = "MONTH_DAY";
	var MONTH_NUM_DAY = "MONTH_NUM_DAY";
	var MONTH_WEEKDAY_DAY = "MONTH_WEEKDAY_DAY";
	var YEAR = "YEAR";
	var YEAR_MONTH = "YEAR_MONTH";
	var YEAR_MONTH_ABBR = "YEAR_MONTH_ABBR";
	var YEAR_MONTH_ABBR_DAY = "YEAR_MONTH_ABBR_DAY";
	var YEAR_MONTH_DAY = "YEAR_MONTH_DAY";
	var YEAR_MONTH_NUM = "YEAR_MONTH_NUM";
	var YEAR_MONTH_NUM_DAY = "YEAR_MONTH_NUM_DAY";
	var YEAR_MONTH_WEEKDAY_DAY = "YEAR_MONTH_WEEKDAY_DAY";
	var YEAR_QUARTER = "YEAR_QUARTER";
	var YEAR_QUARTER_ABBR = "YEAR_QUARTER_ABBR";
}
