package google.apps.script;

@:require(google_apps_script)
@:native("MimeType")
@:enum abstract MimeType(String) to String {
	var GOOGLE_APPS_SCRIPT = "GOOGLE_APPS_SCRIPT";
	var GOOGLE_DRAWINGS = "GOOGLE_DRAWINGS";
	var GOOGLE_DOCS = "GOOGLE_DOCS";
	var GOOGLE_FORMS = "GOOGLE_FORMS";
	var GOOGLE_SHEETS = "GOOGLE_SHEETS";
	var GOOGLE_SLIDES = "GOOGLE_SLIDES";
	var FOLDER = "FOLDER";
	var BMP = "BMP";
	var GIF = "GIF";
	var JPEG = "JPEG";
	var PNG = "PNG";
	var SVG = "SVG";
	var PDF = "PDF";
	var CSS = "CSS";
	var CSV = "CSV";
	var HTML = "HTML";
	var JAVASCRIPT = "JAVASCRIPT";
	var PLAIN_TEXT = "PLAIN_TEXT";
	var RTF = "RTF";
	var OPENDOCUMENT_GRAPHICS = "OPENDOCUMENT_GRAPHICS";
	var OPENDOCUMENT_PRESENTATION = "OPENDOCUMENT_PRESENTATION";
	var OPENDOCUMENT_SPREADSHEET = "OPENDOCUMENT_SPREADSHEET";
	var OPENDOCUMENT_TEXT = "OPENDOCUMENT_TEXT";
	var MICROSOFT_EXCEL = "MICROSOFT_EXCEL";
	var MICROSOFT_EXCEL_LEGACY = "MICROSOFT_EXCEL_LEGACY";
	var MICROSOFT_POWERPOINT = "MICROSOFT_POWERPOINT";
	var MICROSOFT_POWERPOINT_LEGACY = "MICROSOFT_POWERPOINT_LEGACY";
	var MICROSOFT_WORD = "MICROSOFT_WORD";
	var MICROSOFT_WORD_LEGACY = "MICROSOFT_WORD_LEGACY";
	var ZIP = "ZIP";
}
