package google.apps.script;

@:fakeEnum(String)
@:native("MimeType")
enum MimeType {
	GOOGLE_APPS_SCRIPT;
	GOOGLE_DRAWINGS;
	GOOGLE_DOCS;
	GOOGLE_FORMS;
	GOOGLE_SHEETS;
	GOOGLE_SLIDES;
	FOLDER;
	BMP;
	GIF;
	JPEG;
	PNG;
	SVG;
	PDF;
	CSS;
	CSV;
	HTML;
	JAVASCRIPT;
	PLAIN_TEXT;
	RTF;
	OPENDOCUMENT_GRAPHICS;
	OPENDOCUMENT_PRESENTATION;
	OPENDOCUMENT_SPREADSHEET;
	OPENDOCUMENT_TEXT;
	MICROSOFT_EXCEL;
	MICROSOFT_EXCEL_LEGACY;
	MICROSOFT_POWERPOINT;
	MICROSOFT_POWERPOINT_LEGACY;
	MICROSOFT_WORD;
	MICROSOFT_WORD_LEGACY;
	ZIP;
}
